apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
 labels:
    app: nodejs-bluegreen
    app.kubernetes.io/component: nodejs-bluegreen
    app.kubernetes.io/instance: nodejs-bluegreen
  name: nodejs-bluegreen
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-bluegreen:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: git@github.com:hhellbusch/nodejs-bluegreen.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5