---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-bluegreen
    app.kubernetes.io/component: nodejs-bluegreen
    app.kubernetes.io/instance: nodejs-bluegreen
  name: nodejs-bluegreen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: nodejs-bluegreen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: nodejs-bluegreen
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/nodejs-bluegreen-dev/nodejs-bluegreen:latest
        imagePullPolicy: IfNotPresent
        name: nodejs-bluegreen
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
