---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-bluegreen
    app.kubernetes.io/component: nodejs-bluegreen
    app.kubernetes.io/instance: nodejs-bluegreen
  name: nodejs-bluegreen
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentConfig: nodejs-bluegreen
  sessionAffinity: None
  type: ClusterIP
